import pandas as pd
from matplotlib import pyplot
import sys


def load_files(name):
    return pd.read_csv(name, sep=";", header=0, index_col=0, parse_dates=True, squeeze=True)


if __name__ == "__main__":
    if len(sys.argv) <= 1:
        print("Usage: %s <file_1> [<file_2> [<file_3> ...]]")
        print("The files should follow the format generated by the analysis script.")
        sys.exit(1)

    files = sys.argv[1:]
    csvs = map(load_files, files)
    df = pd.concat(csvs)

    print("Plotting %d values" % (len(df.index),))

    print(df.head())
    ax = df.plot(title="Sunny hours for each day")
    ax.set_ylabel("Sunny hours (in h)")
    pyplot.show()
