import pandas as pd
from matplotlib import pyplot
import sys


def load_files(name):
    return pd.read_csv(name, sep=";", header=0, index_col=0, parse_dates=True, squeeze=True)


if __name__ == "__main__":
    if len(sys.argv) <= 2:
        print("Usage: %s <outimagefile> <file_1> [<file_2> [<file_3> ...]]")
        print("The <outimagefile> is a path to a file where the resulting graph image should be stored")
        print("The files should follow the format generated by the analysis script.")
        sys.exit(1)

    outfile = sys.argv[1]
    files = sys.argv[2:]
    csvs = map(load_files, files)
    df = pd.concat(csvs)

    print("Plotting %d values" % (len(df.index),))

    fig, ax = pyplot.subplots()
    pl = df.plot( title="Sunny hours for each day", ax=ax)
    ax.xaxis_date()
    pl.set_xlabel("Date")
    pl.set_ylabel("Sunny hours (in h)")
    pyplot.savefig(outfile, bbox_inches='tight')
